### ISSUE TITLE
mariadb_version is not overridable 

### ISSUE THREAD

**Issue by p-thurner** [blunix/role-mariadb#5]
Philipp just had a problem where in his play he could not set mariadb_version to 10.2 - it was always set back to 10.0. We found that variable in vars/{Debian,Ubuntu}.yml, ist it possible that it is overriding the var in the play?

**Comment by surphil** [comment]
1. Die Role war aktualisiert, habe ich auch  noch mal gemacht: `{install_date: 'Fri Sep 14 07:43:07 2018', version: 1.0.3}`(aus .galaxy_install_info).

2. Im play /vagrant/mariadb.xml habe ich die Maria-DB Version angegeben:
```
- name: Install and configure a local MariaDB instance
  hosts: database-servers
  become: yes
  vars:
    pkg_list:
      - name: python-mysqldb

    mariadb_enabled: yes
    mariadb_root_password: s3cr3t
    mariadb_version: 10.2
  
  roles:
    - blunix.role-pkg
    - blunix.role-mariadb
```


3. In /.imported_roles/blunix.role-mariadb/tasks/install/default.yml lasse ich mir die Version ausgeben:

```
- name: install package dependencies
  apt:
    pkg: '{{ pkg_item }}'
    state: installed
    update_cache: no
    install_recommends: no
  with_items: '{{ mariadb_package_dependencies }}'
  loop_control:
    loop_var: pkg_item

- name: add APT repository key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: F1656F24C74CD1D8

- debug:
    msg: "Version {{ mariadb_version }}"

- name: add APT repository 
  apt_repository:
    repo: deb [arch={{ ansible_architecture }}] http://www.ftp.saix.net/DB/mariadb/repo/{{ mariadb_version }}/{{ ansible_distribution | lower }} {{ ansible_lsb.codename }} main
    filename: mariadb

- name: install MariaDB package
  apt:
    pkg: mariadb-server-{{ mariadb_version }}
    state: installed
    update_cache: yes

```
Und bekomme folgende Ausgabe:
```
TASK [blunix.role-mariadb : debug] *******************************************************************************************************************************************************************************************
ok: [dev0.vagrant] => 
  msg: Version 10.0
```
4. Wenn ich die Maria-DB Version  in der Role von Hand setzte:

```
- name: add APT repository
  apt_repository:
    repo: deb [arch={{ ansible_architecture }}] http://www.ftp.saix.net/DB/mariadb/repo/10.2/{{ ansible_distribution | lower }} {{ ansible_lsb.codename }} main
    filename: mariadb
```
bekomme ich folgenden Fehler:

```
TASK [blunix.role-mariadb : add APT repository] ******************************************************************************************************************************************************************************
fatal: [dev0.vagrant]: FAILED! => changed=false 
  module_stderr: |-
    Shared connection to dev0.vagrant closed.
  module_stdout: |-
    Traceback (most recent call last):
      File "/tmp/ansible_LwoFB3/ansible_module_apt_repository.py", line 550, in <module>
        main()
      File "/tmp/ansible_LwoFB3/ansible_module_apt_repository.py", line 542, in main
        cache.update()
      File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 487, in update
        raise FetchFailedException(e)
    apt.cache.FetchFailedException: W:chown to _apt:root of directory /var/lib/apt/lists/partial failed - SetupAPTPartialDirectory (1: Operation not permitted), W:chown to _apt:root of file /var/lib/apt/lists/ppa.launchpad.net_ondrej_php_ubuntu_dists_xenial_InRelease failed - Item::QueueURI (1: Operation not permitted), W:chown to _apt:root of file /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial_InRelease failed - Item::QueueURI (1: Operation not permitted), W:chown to _apt:root of file /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial-updates_InRelease failed - Item::QueueURI (1: Operation not permitted), W:chown to _apt:root of file /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial-backports_InRelease failed - Item::QueueURI (1: Operation not permitted), W:chown to _apt:root of file /var/lib/apt/lists/security.ubuntu.com_ubuntu_dists_xenial-security_InRelease failed - Item::QueueURI (1: Operation not permitted), W:chown to _apt:root of file /var/lib/apt/lists/deb.nodesource.com_node%5f8.x_dists_xenial_InRelease failed - Item::QueueURI (1: Operation not permitted), W:chown to _apt:root of file /var/lib/apt/lists/www.ftp.saix.net_DB_mariadb_repo_10.0_ubuntu_dists_xenial_InRelease failed - Item::QueueURI (1: Operation not permitted), W:Skipping acquire of configured file 'main/binary-x86_64/Packages' as repository 'http://www.ftp.saix.net/DB/mariadb/repo/10.0/ubuntu xenial InRelease' doesn't support architecture 'x86_64', W:chown to _apt:root of file /var/lib/apt/lists/partial/www.ftp.saix.net_DB_mariadb_repo_10.2_ubuntu_dists_xenial_InRelease failed - Item::QueueURI (1: Operation not permitted), W:Skipping acquire of configured file 'main/binary-x86_64/Packages' as repository 'http://www.ftp.saix.net/DB/mariadb/repo/10.2/ubuntu xenial InRelease' doesn't support architecture 'x86_64', W:The repository 'http://www.ftp.saix.net/DB/mariadb/repo/12.2/ubuntu xenial Release' does not have a Release file., W:Data from such a repository can't be authenticated and is therefore potentially dangerous to use., W:See apt-secure(8) manpage for repository creation and user configuration details., E:Failed to fetch http://www.ftp.saix.net/DB/mariadb/repo/12.2/ubuntu/dists/xenial/main/binary-x86_64/Packages  404  Not Found, E:Some index files failed to download. They have been ignored, or old ones used instead.
  msg: MODULE FAILURE
  rc: 1
```
